apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  containers:
  - name: cuda-vector-add
    image: "nvidia/cuda:11.0.3-base-ubuntu20.04"
    command: ["sh", "-c"]
    args:
      - apt-get update && apt-get install -y cuda-samples-11-0 && cd /usr/local/cuda/samples/0_Simple/vectorAdd && make && ./vectorAdd;
    resources:
      limits:
        nvidia.com/gpu: 1
