apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tgi-podmonitor
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: huggingface-model
  podMetricsEndpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    any: true