global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'tgi-server'
    static_configs:
      - targets: ['ec2-52-41-124-229.us-west-2.compute.amazonaws.com:8080']