global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'tgi-server'
    static_configs:
      - targets: ['tgi:80']
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi:8000']
