{
 "title": "Data Dashboard",
 "tags": [ "rayVersion:2.34.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "label_values(ray_data_allocated_bytes{}, SessionName)"
    }
   },
   {
    "name": "DatasetID",
    "query": {
     "query": "label_values(ray_data_allocated_bytes{}, dataset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes Spilled",
   "type": "graph",
   "description": "Amount spilled by dataset operators. DataContext.enable_get_object_locations_for_metrics must be set to True to report this metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_spilled_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Spilled: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Allocated",
   "type": "graph",
   "description": "Amount allocated by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_allocated_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Allocated: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Freed",
   "type": "graph",
   "description": "Amount freed by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_freed_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Freed: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Amount of memory store used by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_current_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Current Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_cpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "CPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_gpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "GPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Outputted",
   "type": "graph",
   "description": "Total bytes outputted by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_output_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Outputted: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Rows Outputted",
   "type": "graph",
   "description": "Total rows outputted by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "rows" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_output_rows{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Rows Outputted: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Blocks Received by Operator",
   "type": "graph",
   "description": "Number of input blocks received by operator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_inputs_received{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Blocks Received: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Blocks Received by Operator",
   "type": "graph",
   "description": "Byte size of input blocks received by operator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_bytes_inputs_received{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Received: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Blocks Processed by Tasks",
   "type": "graph",
   "description": "Number of input blocks that operator's tasks have finished processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_task_inputs_processed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Blocks Processed: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Bytes Processed by Tasks",
   "type": "graph",
   "description": "Byte size of input blocks that operator's tasks have finished processing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_bytes_task_inputs_processed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Processed: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Bytes Submitted to Tasks",
   "type": "graph",
   "description": "Byte size of input blocks passed to submitted tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_bytes_inputs_of_submitted_tasks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Submitted: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Blocks Generated by Tasks",
   "type": "graph",
   "description": "Number of output blocks generated by tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Blocks Generated: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Generated by Tasks",
   "type": "graph",
   "description": "Byte size of output blocks generated by tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_bytes_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Generated: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Rows Generated by Tasks",
   "type": "graph",
   "description": "Number of rows in generated output blocks from finished tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "rows" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_rows_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Rows Generated: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Output Blocks Taken by Downstream Operators",
   "type": "graph",
   "description": "Number of output blocks that are already taken by downstream operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_outputs_taken{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Blocks Taken: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Output Bytes Taken by Downstream Operators",
   "type": "graph",
   "description": "Byte size of output blocks that are already taken by downstream operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_bytes_outputs_taken{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Taken: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Submitted Tasks",
   "type": "graph",
   "description": "Number of submitted tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_submitted{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Submitted Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "description": "Number of running tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_running{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Running Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Tasks with output blocks",
   "type": "graph",
   "description": "Number of tasks that already have output.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_have_outputs{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Tasks with output blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Finished Tasks",
   "type": "graph",
   "description": "Number of finished tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Finished Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "graph",
   "description": "Number of failed tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_failed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Failed Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Block Generation Time",
   "type": "graph",
   "description": "Time spent generating blocks in tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_block_generation_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Block Generation Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Task Submission Backpressure Time",
   "type": "graph",
   "description": "Time spent in task submission backpressure.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_task_submission_backpressure_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Backpressure Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Inqueue Size (Blocks)",
   "type": "graph",
   "description": "Number of blocks in operator's internal input queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_inqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Inqueue Size (Bytes)",
   "type": "graph",
   "description": "Byte size of input blocks in the operator's internal input queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_inqueue{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Outqueue Size (Blocks)",
   "type": "graph",
   "description": "Number of blocks in operator's internal output queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_outqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Outqueue Size (Bytes)",
   "type": "graph",
   "description": "Byte size of output blocks in the operator's internal output queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_outqueue{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Size of Blocks used in Pending Tasks (Bytes)",
   "type": "graph",
   "description": "Byte size of input blocks used by pending tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_pending_task_inputs{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Freed Memory in Object Store (Bytes)",
   "type": "graph",
   "description": "Byte size of freed memory in object store.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_freed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Spilled Memory in Object Store (Bytes)",
   "type": "graph",
   "description": "Byte size of spilled memory in object store.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_spilled{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Iteration Initialization Time",
   "type": "graph",
   "description": "Seconds spent in iterator initialization code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_initialize_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Iteration Blocked Time",
   "type": "graph",
   "description": "Seconds user thread is blocked by iter_batches()",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_total_blocked_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  },
  {
   "title": "Iteration User Time",
   "type": "graph",
   "description": "Seconds spent in user code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_user_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  }
 ]
}